name: ANT CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparation 
        run: |
          sudo apt-get install tree libldap2-dev
      - name: JAVA 
        run: |
          make init
          make patch.apply
          make install.jdk.local
          make install.ant.local
          export JAVA_HOME=${GITHUB_WORKSPACE}/ComponentDB-src/support/java/linux-x86_64
          export ANT_HOME=${GITHUB_WORKSPACE}}/ComponentDB-src/support/ant/
          export PATH=${ANT_HOME}/bin:$JAVA_HOME/bin:$PATH
          make info.ant
          make vars
          echo "PATH"
          echo ">>> PATH:       $PATH"
          echo ">>> JAVA_HOME : $JAVA_HOME"
          make install.cdbpython
          make build
