name: ANT CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparation 
        run: |
          sudo apt-get install tree ant libjaxb-api-java
      - name: JAVA 
        run: |
          make init
          make patch.apply
          bash ComponentDB-src/support/bin/install_java.sh
          bash ComponentDB-src/support/bin/install_ant.sh
          export JAVA_HOME=${PWD}/ComponentDB-src/support/java/linux-x86_64
          export PATH=$JAVA_HOME/bin:$PATH
      - name: Building
        run: |
          echo "JAVA_PATH=${PWD}/ComponentDB-src/support/java/linux-x86_64/bin" > configure/CPNFIG_COMMON.local
          echo "ANT_HOME=${PWD}/ComponentDB-src/support/ant" >>  configure/CPNFIG_COMMON.local
          make info.ant
          make vars
          echo $PATH
          make build
      - name: A WAR file
        run: |
          mkdir WARFILE
          cd WARFILE && jar xf ComponentDB-src/src/java/CdbWebPortal/dist/CdbWebPortal.war
          tree -L 2 WARFILE
      - name: Compare build and WAR file
        run: diff -rq ComponentDB-src/src/java/CdbWebPortal/build/web/ WARFILE/
