name: ANT CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparation 
        run: |
          sudo apt-get install tree ant
      - name: JAVA 
        run: |
          make init
          make patch.apply
          make install.jdk.local
          export JAVA_HOME=${GITHUB_WORKSPACE}/ComponentDB-src/support/java/linux-x86_64
          export PATH=$JAVA_HOME/bin:$PATH
          make info.ant
          make vars
          echo "PATH"
          echo ">>> PATH:       $PATH"
          echo ">>> JAVA_HOME : $JAVA_HOME"
          make build
      - name: A WAR file
        run: |
          mkdir WARFILE
          cd WARFILE && jar xf ComponentDB-src/src/java/CdbWebPortal/dist/CdbWebPortal.war
          tree -L 2 WARFILE
      - name: Compare build and WAR file
        run: diff -rq ComponentDB-src/src/java/CdbWebPortal/build/web/ WARFILE/
